-- VHDL module instantiation generated by SCUBA Diamond (64-bit) 3.10.3.144
-- Module  Version: 7.5
-- Thu Jul 11 10:58:36 2019

-- parameterized module component declaration
component RAM_DQ_16x1024
    port (Clock: in  std_logic; ClockEn: in  std_logic; 
        Reset: in  std_logic; WE: in  std_logic; 
        Address: in  std_logic_vector(9 downto 0); 
        Data: in  std_logic_vector(15 downto 0); 
        Q: out  std_logic_vector(15 downto 0));
end component;

-- parameterized module component instance
__ : RAM_DQ_16x1024
    port map (Clock=>__, ClockEn=>__, Reset=>__, WE=>__, Address(9 downto 0)=>__, 
        Data(15 downto 0)=>__, Q(15 downto 0)=>__);
