-- VHDL module instantiation generated by SCUBA Diamond (64-bit) 3.10.3.144
-- Module  Version: 5.4
-- Thu Oct 03 09:24:55 2019

-- parameterized module component declaration
component ROM_16x8192
    port (Address: in  std_logic_vector(12 downto 0); 
        OutClock: in  std_logic; OutClockEn: in  std_logic; 
        Reset: in  std_logic; Q: out  std_logic_vector(15 downto 0));
end component;

-- parameterized module component instance
__ : ROM_16x8192
    port map (Address(12 downto 0)=>__, OutClock=>__, OutClockEn=>__, 
        Reset=>__, Q(15 downto 0)=>__);
